// The surface a tool service implements and gatewayd dispatches one attempt to.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: flory/gateway/v1/execution.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolExecutionService_Execute_FullMethodName = "/flory.gateway.v1.ToolExecutionService/Execute"
)

// ToolExecutionServiceClient is the client API for ToolExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToolExecutionServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type toolExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolExecutionServiceClient(cc grpc.ClientConnInterface) ToolExecutionServiceClient {
	return &toolExecutionServiceClient{cc}
}

func (c *toolExecutionServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, ToolExecutionService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolExecutionServiceServer is the server API for ToolExecutionService service.
// All implementations must embed UnimplementedToolExecutionServiceServer
// for forward compatibility.
type ToolExecutionServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedToolExecutionServiceServer()
}

// UnimplementedToolExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolExecutionServiceServer struct{}

func (UnimplementedToolExecutionServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedToolExecutionServiceServer) mustEmbedUnimplementedToolExecutionServiceServer() {}
func (UnimplementedToolExecutionServiceServer) testEmbeddedByValue()                              {}

// UnsafeToolExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolExecutionServiceServer will
// result in compilation errors.
type UnsafeToolExecutionServiceServer interface {
	mustEmbedUnimplementedToolExecutionServiceServer()
}

func RegisterToolExecutionServiceServer(s grpc.ServiceRegistrar, srv ToolExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedToolExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolExecutionService_ServiceDesc, srv)
}

func _ToolExecutionService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolExecutionServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolExecutionService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolExecutionServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolExecutionService_ServiceDesc is the grpc.ServiceDesc for ToolExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flory.gateway.v1.ToolExecutionService",
	HandlerType: (*ToolExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _ToolExecutionService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flory/gateway/v1/execution.proto",
}
