// The surface a tool service implements and gatewayd dispatches one attempt to.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: flory/gateway/v1/execution.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The executor-facing result vocabulary, identical to the Coordinator's.
type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	Outcome_OUTCOME_SUCCEEDED   Outcome = 1
	// The same idempotent operation may be attempted again -- by the executor, never here.
	Outcome_OUTCOME_RETRYABLE_FAILURE Outcome = 2
	Outcome_OUTCOME_PERMANENT_FAILURE Outcome = 3
	// Requires a pivot status query to resolve.
	Outcome_OUTCOME_UNKNOWN Outcome = 4
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_SUCCEEDED",
		2: "OUTCOME_RETRYABLE_FAILURE",
		3: "OUTCOME_PERMANENT_FAILURE",
		4: "OUTCOME_UNKNOWN",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":       0,
		"OUTCOME_SUCCEEDED":         1,
		"OUTCOME_RETRYABLE_FAILURE": 2,
		"OUTCOME_PERMANENT_FAILURE": 3,
		"OUTCOME_UNKNOWN":           4,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_flory_gateway_v1_execution_proto_enumTypes[0].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_flory_gateway_v1_execution_proto_enumTypes[0]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_flory_gateway_v1_execution_proto_rawDescGZIP(), []int{0}
}

// Exactly one logical attempt. The gateway never generates a second one.
type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	VertexId       string                 `protobuf:"bytes,2,opt,name=vertex_id,json=vertexId,proto3" json:"vertex_id,omitempty"`
	ScopeId        string                 `protobuf:"bytes,3,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	AttemptNo      uint32                 `protobuf:"varint,4,opt,name=attempt_no,json=attemptNo,proto3" json:"attempt_no,omitempty"`
	ToolId         string                 `protobuf:"bytes,5,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ToolVersion    string                 `protobuf:"bytes,6,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	ToolViewDigest string                 `protobuf:"bytes,7,opt,name=tool_view_digest,json=toolViewDigest,proto3" json:"tool_view_digest,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Arguments as JSON text, already validated against the frozen input schema.
	// JSON text rather than google.protobuf.Struct, whose numbers are doubles and
	// would silently lose integer fidelity.
	Arguments     string                 `protobuf:"bytes,9,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_flory_gateway_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecuteRequest) GetVertexId() string {
	if x != nil {
		return x.VertexId
	}
	return ""
}

func (x *ExecuteRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *ExecuteRequest) GetAttemptNo() uint32 {
	if x != nil {
		return x.AttemptNo
	}
	return 0
}

func (x *ExecuteRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ExecuteRequest) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *ExecuteRequest) GetToolViewDigest() string {
	if x != nil {
		return x.ToolViewDigest
	}
	return ""
}

func (x *ExecuteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecuteRequest) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ExecuteRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type ExecuteResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Outcome Outcome                `protobuf:"varint,1,opt,name=outcome,proto3,enum=flory.gateway.v1.Outcome" json:"outcome,omitempty"`
	// Result as JSON text; empty is equivalent to an empty object.
	Result        string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_flory_gateway_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *ExecuteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_flory_gateway_v1_execution_proto protoreflect.FileDescriptor

const file_flory_gateway_v1_execution_proto_rawDesc = "" +
	"\n" +
	" flory/gateway/v1/execution.proto\x12\x10flory.gateway.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x02\n" +
	"\x0eExecuteRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tvertex_id\x18\x02 \x01(\tR\bvertexId\x12\x19\n" +
	"\bscope_id\x18\x03 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"attempt_no\x18\x04 \x01(\rR\tattemptNo\x12\x17\n" +
	"\atool_id\x18\x05 \x01(\tR\x06toolId\x12!\n" +
	"\ftool_version\x18\x06 \x01(\tR\vtoolVersion\x12(\n" +
	"\x10tool_view_digest\x18\a \x01(\tR\x0etoolViewDigest\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12\x1c\n" +
	"\targuments\x18\t \x01(\tR\targuments\x126\n" +
	"\bdeadline\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"t\n" +
	"\x0fExecuteResponse\x123\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x19.flory.gateway.v1.OutcomeR\aoutcome\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\x8c\x01\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OUTCOME_SUCCEEDED\x10\x01\x12\x1d\n" +
	"\x19OUTCOME_RETRYABLE_FAILURE\x10\x02\x12\x1d\n" +
	"\x19OUTCOME_PERMANENT_FAILURE\x10\x03\x12\x13\n" +
	"\x0fOUTCOME_UNKNOWN\x10\x042f\n" +
	"\x14ToolExecutionService\x12N\n" +
	"\aExecute\x12 .flory.gateway.v1.ExecuteRequest\x1a!.flory.gateway.v1.ExecuteResponseBLZJgithub.com/linuxb/flory-ai/gatewayd/internal/pb/flory/gateway/v1;gatewayv1b\x06proto3"

var (
	file_flory_gateway_v1_execution_proto_rawDescOnce sync.Once
	file_flory_gateway_v1_execution_proto_rawDescData []byte
)

func file_flory_gateway_v1_execution_proto_rawDescGZIP() []byte {
	file_flory_gateway_v1_execution_proto_rawDescOnce.Do(func() {
		file_flory_gateway_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flory_gateway_v1_execution_proto_rawDesc), len(file_flory_gateway_v1_execution_proto_rawDesc)))
	})
	return file_flory_gateway_v1_execution_proto_rawDescData
}

var file_flory_gateway_v1_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flory_gateway_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_flory_gateway_v1_execution_proto_goTypes = []any{
	(Outcome)(0),                  // 0: flory.gateway.v1.Outcome
	(*ExecuteRequest)(nil),        // 1: flory.gateway.v1.ExecuteRequest
	(*ExecuteResponse)(nil),       // 2: flory.gateway.v1.ExecuteResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_flory_gateway_v1_execution_proto_depIdxs = []int32{
	3, // 0: flory.gateway.v1.ExecuteRequest.deadline:type_name -> google.protobuf.Timestamp
	0, // 1: flory.gateway.v1.ExecuteResponse.outcome:type_name -> flory.gateway.v1.Outcome
	1, // 2: flory.gateway.v1.ToolExecutionService.Execute:input_type -> flory.gateway.v1.ExecuteRequest
	2, // 3: flory.gateway.v1.ToolExecutionService.Execute:output_type -> flory.gateway.v1.ExecuteResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_flory_gateway_v1_execution_proto_init() }
func file_flory_gateway_v1_execution_proto_init() {
	if File_flory_gateway_v1_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flory_gateway_v1_execution_proto_rawDesc), len(file_flory_gateway_v1_execution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flory_gateway_v1_execution_proto_goTypes,
		DependencyIndexes: file_flory_gateway_v1_execution_proto_depIdxs,
		EnumInfos:         file_flory_gateway_v1_execution_proto_enumTypes,
		MessageInfos:      file_flory_gateway_v1_execution_proto_msgTypes,
	}.Build()
	File_flory_gateway_v1_execution_proto = out.File
	file_flory_gateway_v1_execution_proto_goTypes = nil
	file_flory_gateway_v1_execution_proto_depIdxs = nil
}
