// The gatewayd south-side registration surface, spoken by the tool-service SDK.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: flory/gateway/v1/registry.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServingStatus int32

const (
	ServingStatus_SERVING_STATUS_UNSPECIFIED ServingStatus = 0
	ServingStatus_SERVING_STATUS_SERVING     ServingStatus = 1
	ServingStatus_SERVING_STATUS_NOT_SERVING ServingStatus = 2
)

// Enum value maps for ServingStatus.
var (
	ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
	}
	ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_NOT_SERVING": 2,
	}
)

func (x ServingStatus) Enum() *ServingStatus {
	p := new(ServingStatus)
	*p = x
	return p
}

func (x ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_flory_gateway_v1_registry_proto_enumTypes[0].Descriptor()
}

func (ServingStatus) Type() protoreflect.EnumType {
	return &file_flory_gateway_v1_registry_proto_enumTypes[0]
}

func (x ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServingStatus.Descriptor instead.
func (ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{0}
}

// The closed registration-rejection vocabulary from design document 09 section 3.
// Both SDK languages report identical codes.
type AdmissionCode int32

const (
	AdmissionCode_ADMISSION_CODE_UNSPECIFIED AdmissionCode = 0
	// G1: identity or schema fields missing, or a schema that does not compile.
	AdmissionCode_ADMISSION_CODE_MALFORMED_CONTRACT AdmissionCode = 1
	// G2: mode tcc without a complete, idempotent, timed try-confirm-cancel triple.
	AdmissionCode_ADMISSION_CODE_INCOMPLETE_TCC_TRIPLE AdmissionCode = 2
	// G3: mode saga without a registered idempotent compensation.
	AdmissionCode_ADMISSION_CODE_INCOMPLETE_SAGA_COMPENSATION AdmissionCode = 3
	// G4: an effect class that disagrees with the declared undo path.
	AdmissionCode_ADMISSION_CODE_MISLABELLED_EFFECT_CLASS AdmissionCode = 4
	// G5: compensation declared as snapshot restore rather than delta.
	AdmissionCode_ADMISSION_CODE_NON_DELTA_COMPENSATION AdmissionCode = 5
	// G6: a referenced companion tool is absent from the view.
	AdmissionCode_ADMISSION_CODE_UNRESOLVED_COMPANION AdmissionCode = 6
	// G7: a published (tool_id, tool_version) was re-registered with a different body.
	AdmissionCode_ADMISSION_CODE_IMMUTABLE_VERSION_CONFLICT AdmissionCode = 7
	// G8: a companion reference is self-referential or cyclic.
	//
	// There is deliberately no code for "a derived attribute was declared":
	// is_pivot and compensable have no field in ToolContract, so the obligation
	// is discharged by the schema rather than by a runtime check.
	AdmissionCode_ADMISSION_CODE_INVALID_COMPANION_REFERENCE AdmissionCode = 8
)

// Enum value maps for AdmissionCode.
var (
	AdmissionCode_name = map[int32]string{
		0: "ADMISSION_CODE_UNSPECIFIED",
		1: "ADMISSION_CODE_MALFORMED_CONTRACT",
		2: "ADMISSION_CODE_INCOMPLETE_TCC_TRIPLE",
		3: "ADMISSION_CODE_INCOMPLETE_SAGA_COMPENSATION",
		4: "ADMISSION_CODE_MISLABELLED_EFFECT_CLASS",
		5: "ADMISSION_CODE_NON_DELTA_COMPENSATION",
		6: "ADMISSION_CODE_UNRESOLVED_COMPANION",
		7: "ADMISSION_CODE_IMMUTABLE_VERSION_CONFLICT",
		8: "ADMISSION_CODE_INVALID_COMPANION_REFERENCE",
	}
	AdmissionCode_value = map[string]int32{
		"ADMISSION_CODE_UNSPECIFIED":                  0,
		"ADMISSION_CODE_MALFORMED_CONTRACT":           1,
		"ADMISSION_CODE_INCOMPLETE_TCC_TRIPLE":        2,
		"ADMISSION_CODE_INCOMPLETE_SAGA_COMPENSATION": 3,
		"ADMISSION_CODE_MISLABELLED_EFFECT_CLASS":     4,
		"ADMISSION_CODE_NON_DELTA_COMPENSATION":       5,
		"ADMISSION_CODE_UNRESOLVED_COMPANION":         6,
		"ADMISSION_CODE_IMMUTABLE_VERSION_CONFLICT":   7,
		"ADMISSION_CODE_INVALID_COMPANION_REFERENCE":  8,
	}
)

func (x AdmissionCode) Enum() *AdmissionCode {
	p := new(AdmissionCode)
	*p = x
	return p
}

func (x AdmissionCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdmissionCode) Descriptor() protoreflect.EnumDescriptor {
	return file_flory_gateway_v1_registry_proto_enumTypes[1].Descriptor()
}

func (AdmissionCode) Type() protoreflect.EnumType {
	return &file_flory_gateway_v1_registry_proto_enumTypes[1]
}

func (x AdmissionCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdmissionCode.Descriptor instead.
func (AdmissionCode) EnumDescriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{1}
}

type ToolState int32

const (
	ToolState_TOOL_STATE_UNSPECIFIED ToolState = 0
	// Structurally valid but waiting on a companion that no service has registered yet.
	ToolState_TOOL_STATE_PENDING ToolState = 1
	// Published in the current tool view.
	ToolState_TOOL_STATE_ADMITTED ToolState = 2
	ToolState_TOOL_STATE_REJECTED ToolState = 3
)

// Enum value maps for ToolState.
var (
	ToolState_name = map[int32]string{
		0: "TOOL_STATE_UNSPECIFIED",
		1: "TOOL_STATE_PENDING",
		2: "TOOL_STATE_ADMITTED",
		3: "TOOL_STATE_REJECTED",
	}
	ToolState_value = map[string]int32{
		"TOOL_STATE_UNSPECIFIED": 0,
		"TOOL_STATE_PENDING":     1,
		"TOOL_STATE_ADMITTED":    2,
		"TOOL_STATE_REJECTED":    3,
	}
)

func (x ToolState) Enum() *ToolState {
	p := new(ToolState)
	*p = x
	return p
}

func (x ToolState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolState) Descriptor() protoreflect.EnumDescriptor {
	return file_flory_gateway_v1_registry_proto_enumTypes[2].Descriptor()
}

func (ToolState) Type() protoreflect.EnumType {
	return &file_flory_gateway_v1_registry_proto_enumTypes[2]
}

func (x ToolState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolState.Descriptor instead.
func (ToolState) EnumDescriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{2}
}

// One running instance of a tool service. Never part of the tool-view digest:
// membership may change so the gateway can route a pinned contract to a healthy
// instance, and that must not change tool semantics or version identity.
type InstanceInfo struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	RouteId    string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	// gRPC dial target of this instance, "host:port".
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// How long the registration lease survives without a heartbeat.
	LeaseTtlMs    uint32 `protobuf:"varint,4,opt,name=lease_ttl_ms,json=leaseTtlMs,proto3" json:"lease_ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceInfo) Reset() {
	*x = InstanceInfo{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInfo) ProtoMessage() {}

func (x *InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInfo.ProtoReflect.Descriptor instead.
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceInfo) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *InstanceInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *InstanceInfo) GetLeaseTtlMs() uint32 {
	if x != nil {
		return x.LeaseTtlMs
	}
	return 0
}

// The instance's own view of its readiness, carried on every heartbeat. The
// gateway additionally probes grpc.health.v1.Health; both must agree before an
// instance is routable.
type HealthReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServingStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=flory.gateway.v1.ServingStatus" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *HealthReport) GetStatus() ServingStatus {
	if x != nil {
		return x.Status
	}
	return ServingStatus_SERVING_STATUS_UNSPECIFIED
}

func (x *HealthReport) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ToolStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ToolVersion   string                 `protobuf:"bytes,2,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	State         ToolState              `protobuf:"varint,3,opt,name=state,proto3,enum=flory.gateway.v1.ToolState" json:"state,omitempty"`
	Code          AdmissionCode          `protobuf:"varint,4,opt,name=code,proto3,enum=flory.gateway.v1.AdmissionCode" json:"code,omitempty"`
	Detail        string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolStatus) Reset() {
	*x = ToolStatus{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStatus) ProtoMessage() {}

func (x *ToolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStatus.ProtoReflect.Descriptor instead.
func (*ToolStatus) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *ToolStatus) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolStatus) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *ToolStatus) GetState() ToolState {
	if x != nil {
		return x.State
	}
	return ToolState_TOOL_STATE_UNSPECIFIED
}

func (x *ToolStatus) GetCode() AdmissionCode {
	if x != nil {
		return x.Code
	}
	return AdmissionCode_ADMISSION_CODE_UNSPECIFIED
}

func (x *ToolStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// A pointer to one immutable published tool view.
type ToolViewRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ToolViewRef    string                 `protobuf:"bytes,1,opt,name=tool_view_ref,json=toolViewRef,proto3" json:"tool_view_ref,omitempty"`
	ToolViewDigest string                 `protobuf:"bytes,2,opt,name=tool_view_digest,json=toolViewDigest,proto3" json:"tool_view_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolViewRef) Reset() {
	*x = ToolViewRef{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolViewRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolViewRef) ProtoMessage() {}

func (x *ToolViewRef) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolViewRef.ProtoReflect.Descriptor instead.
func (*ToolViewRef) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ToolViewRef) GetToolViewRef() string {
	if x != nil {
		return x.ToolViewRef
	}
	return ""
}

func (x *ToolViewRef) GetToolViewDigest() string {
	if x != nil {
		return x.ToolViewDigest
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *InstanceInfo          `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Tools         []*ToolContract        `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	Health        *HealthReport          `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetInstance() *InstanceInfo {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *RegisterRequest) GetTools() []*ToolContract {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *RegisterRequest) GetHealth() *HealthReport {
	if x != nil {
		return x.Health
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*ToolStatus          `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	View          *ToolViewRef           `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetStatuses() []*ToolStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *RegisterResponse) GetView() *ToolViewRef {
	if x != nil {
		return x.View
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Health        *HealthReport          `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetHealth() *HealthReport {
	if x != nil {
		return x.Health
	}
	return nil
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False after a gateway restart, which tells the SDK to register again.
	KnownInstance bool         `protobuf:"varint,1,opt,name=known_instance,json=knownInstance,proto3" json:"known_instance,omitempty"`
	View          *ToolViewRef `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetKnownInstance() bool {
	if x != nil {
		return x.KnownInstance
	}
	return false
}

func (x *HeartbeatResponse) GetView() *ToolViewRef {
	if x != nil {
		return x.View
	}
	return nil
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{8}
}

func (x *DeregisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{9}
}

type GetToolViewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty resolves the current view; a digest resolves that exact frozen view.
	ToolViewDigest string `protobuf:"bytes,1,opt,name=tool_view_digest,json=toolViewDigest,proto3" json:"tool_view_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetToolViewRequest) Reset() {
	*x = GetToolViewRequest{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolViewRequest) ProtoMessage() {}

func (x *GetToolViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolViewRequest.ProtoReflect.Descriptor instead.
func (*GetToolViewRequest) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{10}
}

func (x *GetToolViewRequest) GetToolViewDigest() string {
	if x != nil {
		return x.ToolViewDigest
	}
	return ""
}

type GetToolViewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	View  *ToolViewRef           `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	// The canonical tool-view document, verbatim, so the caller can verify the digest.
	Document      string `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolViewResponse) Reset() {
	*x = GetToolViewResponse{}
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolViewResponse) ProtoMessage() {}

func (x *GetToolViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolViewResponse.ProtoReflect.Descriptor instead.
func (*GetToolViewResponse) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_registry_proto_rawDescGZIP(), []int{11}
}

func (x *GetToolViewResponse) GetView() *ToolViewRef {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *GetToolViewResponse) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

var File_flory_gateway_v1_registry_proto protoreflect.FileDescriptor

const file_flory_gateway_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1fflory/gateway/v1/registry.proto\x12\x10flory.gateway.v1\x1a$flory/gateway/v1/tool_contract.proto\"\x84\x01\n" +
	"\fInstanceInfo\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12 \n" +
	"\flease_ttl_ms\x18\x04 \x01(\rR\n" +
	"leaseTtlMs\"_\n" +
	"\fHealthReport\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.flory.gateway.v1.ServingStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\xc8\x01\n" +
	"\n" +
	"ToolStatus\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12!\n" +
	"\ftool_version\x18\x02 \x01(\tR\vtoolVersion\x121\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1b.flory.gateway.v1.ToolStateR\x05state\x123\n" +
	"\x04code\x18\x04 \x01(\x0e2\x1f.flory.gateway.v1.AdmissionCodeR\x04code\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\"[\n" +
	"\vToolViewRef\x12\"\n" +
	"\rtool_view_ref\x18\x01 \x01(\tR\vtoolViewRef\x12(\n" +
	"\x10tool_view_digest\x18\x02 \x01(\tR\x0etoolViewDigest\"\xbb\x01\n" +
	"\x0fRegisterRequest\x12:\n" +
	"\binstance\x18\x01 \x01(\v2\x1e.flory.gateway.v1.InstanceInfoR\binstance\x124\n" +
	"\x05tools\x18\x02 \x03(\v2\x1e.flory.gateway.v1.ToolContractR\x05tools\x126\n" +
	"\x06health\x18\x03 \x01(\v2\x1e.flory.gateway.v1.HealthReportR\x06health\"\x7f\n" +
	"\x10RegisterResponse\x128\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1c.flory.gateway.v1.ToolStatusR\bstatuses\x121\n" +
	"\x04view\x18\x02 \x01(\v2\x1d.flory.gateway.v1.ToolViewRefR\x04view\"k\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x126\n" +
	"\x06health\x18\x02 \x01(\v2\x1e.flory.gateway.v1.HealthReportR\x06health\"m\n" +
	"\x11HeartbeatResponse\x12%\n" +
	"\x0eknown_instance\x18\x01 \x01(\bR\rknownInstance\x121\n" +
	"\x04view\x18\x02 \x01(\v2\x1d.flory.gateway.v1.ToolViewRefR\x04view\"4\n" +
	"\x11DeregisterRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x14\n" +
	"\x12DeregisterResponse\">\n" +
	"\x12GetToolViewRequest\x12(\n" +
	"\x10tool_view_digest\x18\x01 \x01(\tR\x0etoolViewDigest\"d\n" +
	"\x13GetToolViewResponse\x121\n" +
	"\x04view\x18\x01 \x01(\v2\x1d.flory.gateway.v1.ToolViewRefR\x04view\x12\x1a\n" +
	"\bdocument\x18\x02 \x01(\tR\bdocument*k\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02*\x91\x03\n" +
	"\rAdmissionCode\x12\x1e\n" +
	"\x1aADMISSION_CODE_UNSPECIFIED\x10\x00\x12%\n" +
	"!ADMISSION_CODE_MALFORMED_CONTRACT\x10\x01\x12(\n" +
	"$ADMISSION_CODE_INCOMPLETE_TCC_TRIPLE\x10\x02\x12/\n" +
	"+ADMISSION_CODE_INCOMPLETE_SAGA_COMPENSATION\x10\x03\x12+\n" +
	"'ADMISSION_CODE_MISLABELLED_EFFECT_CLASS\x10\x04\x12)\n" +
	"%ADMISSION_CODE_NON_DELTA_COMPENSATION\x10\x05\x12'\n" +
	"#ADMISSION_CODE_UNRESOLVED_COMPANION\x10\x06\x12-\n" +
	")ADMISSION_CODE_IMMUTABLE_VERSION_CONFLICT\x10\a\x12.\n" +
	"*ADMISSION_CODE_INVALID_COMPANION_REFERENCE\x10\b*q\n" +
	"\tToolState\x12\x1a\n" +
	"\x16TOOL_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TOOL_STATE_PENDING\x10\x01\x12\x17\n" +
	"\x13TOOL_STATE_ADMITTED\x10\x02\x12\x17\n" +
	"\x13TOOL_STATE_REJECTED\x10\x032\xef\x02\n" +
	"\x0fRegistryService\x12Q\n" +
	"\bRegister\x12!.flory.gateway.v1.RegisterRequest\x1a\".flory.gateway.v1.RegisterResponse\x12T\n" +
	"\tHeartbeat\x12\".flory.gateway.v1.HeartbeatRequest\x1a#.flory.gateway.v1.HeartbeatResponse\x12W\n" +
	"\n" +
	"Deregister\x12#.flory.gateway.v1.DeregisterRequest\x1a$.flory.gateway.v1.DeregisterResponse\x12Z\n" +
	"\vGetToolView\x12$.flory.gateway.v1.GetToolViewRequest\x1a%.flory.gateway.v1.GetToolViewResponseBLZJgithub.com/linuxb/flory-ai/gatewayd/internal/pb/flory/gateway/v1;gatewayv1b\x06proto3"

var (
	file_flory_gateway_v1_registry_proto_rawDescOnce sync.Once
	file_flory_gateway_v1_registry_proto_rawDescData []byte
)

func file_flory_gateway_v1_registry_proto_rawDescGZIP() []byte {
	file_flory_gateway_v1_registry_proto_rawDescOnce.Do(func() {
		file_flory_gateway_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flory_gateway_v1_registry_proto_rawDesc), len(file_flory_gateway_v1_registry_proto_rawDesc)))
	})
	return file_flory_gateway_v1_registry_proto_rawDescData
}

var file_flory_gateway_v1_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_flory_gateway_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_flory_gateway_v1_registry_proto_goTypes = []any{
	(ServingStatus)(0),          // 0: flory.gateway.v1.ServingStatus
	(AdmissionCode)(0),          // 1: flory.gateway.v1.AdmissionCode
	(ToolState)(0),              // 2: flory.gateway.v1.ToolState
	(*InstanceInfo)(nil),        // 3: flory.gateway.v1.InstanceInfo
	(*HealthReport)(nil),        // 4: flory.gateway.v1.HealthReport
	(*ToolStatus)(nil),          // 5: flory.gateway.v1.ToolStatus
	(*ToolViewRef)(nil),         // 6: flory.gateway.v1.ToolViewRef
	(*RegisterRequest)(nil),     // 7: flory.gateway.v1.RegisterRequest
	(*RegisterResponse)(nil),    // 8: flory.gateway.v1.RegisterResponse
	(*HeartbeatRequest)(nil),    // 9: flory.gateway.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 10: flory.gateway.v1.HeartbeatResponse
	(*DeregisterRequest)(nil),   // 11: flory.gateway.v1.DeregisterRequest
	(*DeregisterResponse)(nil),  // 12: flory.gateway.v1.DeregisterResponse
	(*GetToolViewRequest)(nil),  // 13: flory.gateway.v1.GetToolViewRequest
	(*GetToolViewResponse)(nil), // 14: flory.gateway.v1.GetToolViewResponse
	(*ToolContract)(nil),        // 15: flory.gateway.v1.ToolContract
}
var file_flory_gateway_v1_registry_proto_depIdxs = []int32{
	0,  // 0: flory.gateway.v1.HealthReport.status:type_name -> flory.gateway.v1.ServingStatus
	2,  // 1: flory.gateway.v1.ToolStatus.state:type_name -> flory.gateway.v1.ToolState
	1,  // 2: flory.gateway.v1.ToolStatus.code:type_name -> flory.gateway.v1.AdmissionCode
	3,  // 3: flory.gateway.v1.RegisterRequest.instance:type_name -> flory.gateway.v1.InstanceInfo
	15, // 4: flory.gateway.v1.RegisterRequest.tools:type_name -> flory.gateway.v1.ToolContract
	4,  // 5: flory.gateway.v1.RegisterRequest.health:type_name -> flory.gateway.v1.HealthReport
	5,  // 6: flory.gateway.v1.RegisterResponse.statuses:type_name -> flory.gateway.v1.ToolStatus
	6,  // 7: flory.gateway.v1.RegisterResponse.view:type_name -> flory.gateway.v1.ToolViewRef
	4,  // 8: flory.gateway.v1.HeartbeatRequest.health:type_name -> flory.gateway.v1.HealthReport
	6,  // 9: flory.gateway.v1.HeartbeatResponse.view:type_name -> flory.gateway.v1.ToolViewRef
	6,  // 10: flory.gateway.v1.GetToolViewResponse.view:type_name -> flory.gateway.v1.ToolViewRef
	7,  // 11: flory.gateway.v1.RegistryService.Register:input_type -> flory.gateway.v1.RegisterRequest
	9,  // 12: flory.gateway.v1.RegistryService.Heartbeat:input_type -> flory.gateway.v1.HeartbeatRequest
	11, // 13: flory.gateway.v1.RegistryService.Deregister:input_type -> flory.gateway.v1.DeregisterRequest
	13, // 14: flory.gateway.v1.RegistryService.GetToolView:input_type -> flory.gateway.v1.GetToolViewRequest
	8,  // 15: flory.gateway.v1.RegistryService.Register:output_type -> flory.gateway.v1.RegisterResponse
	10, // 16: flory.gateway.v1.RegistryService.Heartbeat:output_type -> flory.gateway.v1.HeartbeatResponse
	12, // 17: flory.gateway.v1.RegistryService.Deregister:output_type -> flory.gateway.v1.DeregisterResponse
	14, // 18: flory.gateway.v1.RegistryService.GetToolView:output_type -> flory.gateway.v1.GetToolViewResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_flory_gateway_v1_registry_proto_init() }
func file_flory_gateway_v1_registry_proto_init() {
	if File_flory_gateway_v1_registry_proto != nil {
		return
	}
	file_flory_gateway_v1_tool_contract_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flory_gateway_v1_registry_proto_rawDesc), len(file_flory_gateway_v1_registry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flory_gateway_v1_registry_proto_goTypes,
		DependencyIndexes: file_flory_gateway_v1_registry_proto_depIdxs,
		EnumInfos:         file_flory_gateway_v1_registry_proto_enumTypes,
		MessageInfos:      file_flory_gateway_v1_registry_proto_msgTypes,
	}.Build()
	File_flory_gateway_v1_registry_proto = out.File
	file_flory_gateway_v1_registry_proto_goTypes = nil
	file_flory_gateway_v1_registry_proto_depIdxs = nil
}
