// The registration contract a tool service declares to gatewayd.
//
// Every semantic field here participates in the content-addressed tool-view
// digest. Operational facts that must not change a frozen contract's identity
// -- instance membership and health -- live in registry.proto instead.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: flory/gateway/v1/tool_contract.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Side-effect classification from design document 02.
type EffectClass int32

const (
	EffectClass_EFFECT_CLASS_UNSPECIFIED  EffectClass = 0
	EffectClass_EFFECT_CLASS_NONE         EffectClass = 1
	EffectClass_EFFECT_CLASS_BUFFERABLE   EffectClass = 2
	EffectClass_EFFECT_CLASS_REVERSIBLE   EffectClass = 3
	EffectClass_EFFECT_CLASS_IRREVERSIBLE EffectClass = 4
)

// Enum value maps for EffectClass.
var (
	EffectClass_name = map[int32]string{
		0: "EFFECT_CLASS_UNSPECIFIED",
		1: "EFFECT_CLASS_NONE",
		2: "EFFECT_CLASS_BUFFERABLE",
		3: "EFFECT_CLASS_REVERSIBLE",
		4: "EFFECT_CLASS_IRREVERSIBLE",
	}
	EffectClass_value = map[string]int32{
		"EFFECT_CLASS_UNSPECIFIED":  0,
		"EFFECT_CLASS_NONE":         1,
		"EFFECT_CLASS_BUFFERABLE":   2,
		"EFFECT_CLASS_REVERSIBLE":   3,
		"EFFECT_CLASS_IRREVERSIBLE": 4,
	}
)

func (x EffectClass) Enum() *EffectClass {
	p := new(EffectClass)
	*p = x
	return p
}

func (x EffectClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectClass) Descriptor() protoreflect.EnumDescriptor {
	return file_flory_gateway_v1_tool_contract_proto_enumTypes[0].Descriptor()
}

func (EffectClass) Type() protoreflect.EnumType {
	return &file_flory_gateway_v1_tool_contract_proto_enumTypes[0]
}

func (x EffectClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectClass.Descriptor instead.
func (EffectClass) EnumDescriptor() ([]byte, []int) {
	return file_flory_gateway_v1_tool_contract_proto_rawDescGZIP(), []int{0}
}

// Transaction integration supported by a registered tool.
type ToolMode int32

const (
	ToolMode_TOOL_MODE_UNSPECIFIED ToolMode = 0
	ToolMode_TOOL_MODE_PLAIN       ToolMode = 1
	ToolMode_TOOL_MODE_TCC         ToolMode = 2
	ToolMode_TOOL_MODE_SAGA        ToolMode = 3
)

// Enum value maps for ToolMode.
var (
	ToolMode_name = map[int32]string{
		0: "TOOL_MODE_UNSPECIFIED",
		1: "TOOL_MODE_PLAIN",
		2: "TOOL_MODE_TCC",
		3: "TOOL_MODE_SAGA",
	}
	ToolMode_value = map[string]int32{
		"TOOL_MODE_UNSPECIFIED": 0,
		"TOOL_MODE_PLAIN":       1,
		"TOOL_MODE_TCC":         2,
		"TOOL_MODE_SAGA":        3,
	}
)

func (x ToolMode) Enum() *ToolMode {
	p := new(ToolMode)
	*p = x
	return p
}

func (x ToolMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolMode) Descriptor() protoreflect.EnumDescriptor {
	return file_flory_gateway_v1_tool_contract_proto_enumTypes[1].Descriptor()
}

func (ToolMode) Type() protoreflect.EnumType {
	return &file_flory_gateway_v1_tool_contract_proto_enumTypes[1]
}

func (x ToolMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolMode.Descriptor instead.
func (ToolMode) EnumDescriptor() ([]byte, []int) {
	return file_flory_gateway_v1_tool_contract_proto_rawDescGZIP(), []int{1}
}

// How a compensating tool reverses its try. Snapshot restore is rejected at
// registration because only delta compensation commutes with a concurrent
// branch's committed change (AGENTS.md discipline 17).
type CompensationStyle int32

const (
	CompensationStyle_COMPENSATION_STYLE_UNSPECIFIED      CompensationStyle = 0
	CompensationStyle_COMPENSATION_STYLE_NOT_COMPENSATING CompensationStyle = 1
	CompensationStyle_COMPENSATION_STYLE_DELTA            CompensationStyle = 2
	CompensationStyle_COMPENSATION_STYLE_SNAPSHOT         CompensationStyle = 3
)

// Enum value maps for CompensationStyle.
var (
	CompensationStyle_name = map[int32]string{
		0: "COMPENSATION_STYLE_UNSPECIFIED",
		1: "COMPENSATION_STYLE_NOT_COMPENSATING",
		2: "COMPENSATION_STYLE_DELTA",
		3: "COMPENSATION_STYLE_SNAPSHOT",
	}
	CompensationStyle_value = map[string]int32{
		"COMPENSATION_STYLE_UNSPECIFIED":      0,
		"COMPENSATION_STYLE_NOT_COMPENSATING": 1,
		"COMPENSATION_STYLE_DELTA":            2,
		"COMPENSATION_STYLE_SNAPSHOT":         3,
	}
)

func (x CompensationStyle) Enum() *CompensationStyle {
	p := new(CompensationStyle)
	*p = x
	return p
}

func (x CompensationStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompensationStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_flory_gateway_v1_tool_contract_proto_enumTypes[2].Descriptor()
}

func (CompensationStyle) Type() protoreflect.EnumType {
	return &file_flory_gateway_v1_tool_contract_proto_enumTypes[2]
}

func (x CompensationStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompensationStyle.Descriptor instead.
func (CompensationStyle) EnumDescriptor() ([]byte, []int) {
	return file_flory_gateway_v1_tool_contract_proto_rawDescGZIP(), []int{2}
}

// The retry envelope an executor may not exceed for this tool.
//
// The multiplier is expressed in thousandths so the whole contract remains
// integer-valued: the tool-view digest is taken over canonical JSON, and a
// floating-point literal has no canonical text form.
type RetryConstraints struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts      uint32                 `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	InitialBackoffMs uint32                 `protobuf:"varint,2,opt,name=initial_backoff_ms,json=initialBackoffMs,proto3" json:"initial_backoff_ms,omitempty"`
	MultiplierMilli  uint32                 `protobuf:"varint,3,opt,name=multiplier_milli,json=multiplierMilli,proto3" json:"multiplier_milli,omitempty"`
	MaxBackoffMs     uint32                 `protobuf:"varint,4,opt,name=max_backoff_ms,json=maxBackoffMs,proto3" json:"max_backoff_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RetryConstraints) Reset() {
	*x = RetryConstraints{}
	mi := &file_flory_gateway_v1_tool_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryConstraints) ProtoMessage() {}

func (x *RetryConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_tool_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryConstraints.ProtoReflect.Descriptor instead.
func (*RetryConstraints) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_tool_contract_proto_rawDescGZIP(), []int{0}
}

func (x *RetryConstraints) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryConstraints) GetInitialBackoffMs() uint32 {
	if x != nil {
		return x.InitialBackoffMs
	}
	return 0
}

func (x *RetryConstraints) GetMultiplierMilli() uint32 {
	if x != nil {
		return x.MultiplierMilli
	}
	return 0
}

func (x *RetryConstraints) GetMaxBackoffMs() uint32 {
	if x != nil {
		return x.MaxBackoffMs
	}
	return 0
}

// The declared transaction properties of one tool.
//
// `is_pivot` and `compensable` have no field here on purpose: both are derived
// from effect_class and the undo path (02 section 2.1), and a declared copy
// could disagree with what it was derived from.
type TransactionSpec struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EffectClass EffectClass            `protobuf:"varint,1,opt,name=effect_class,json=effectClass,proto3,enum=flory.gateway.v1.EffectClass" json:"effect_class,omitempty"`
	Mode        ToolMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=flory.gateway.v1.ToolMode" json:"mode,omitempty"`
	// JSONPath into the arguments that identifies the idempotency key.
	IdempotencyKeyPath string `protobuf:"bytes,3,opt,name=idempotency_key_path,json=idempotencyKeyPath,proto3" json:"idempotency_key_path,omitempty"`
	// Explicitly optional so an irreversible tool cannot satisfy its obligation
	// to state retry safety by leaving a proto3 bool at its false default.
	IdempotentRetryable *bool  `protobuf:"varint,4,opt,name=idempotent_retryable,json=idempotentRetryable,proto3,oneof" json:"idempotent_retryable,omitempty"`
	TryTimeoutS         uint32 `protobuf:"varint,5,opt,name=try_timeout_s,json=tryTimeoutS,proto3" json:"try_timeout_s,omitempty"`
	ConfirmTool         string `protobuf:"bytes,6,opt,name=confirm_tool,json=confirmTool,proto3" json:"confirm_tool,omitempty"`
	CancelTool          string `protobuf:"bytes,7,opt,name=cancel_tool,json=cancelTool,proto3" json:"cancel_tool,omitempty"`
	CompensateTool      string `protobuf:"bytes,8,opt,name=compensate_tool,json=compensateTool,proto3" json:"compensate_tool,omitempty"`
	StatusTool          string `protobuf:"bytes,9,opt,name=status_tool,json=statusTool,proto3" json:"status_tool,omitempty"`
	// How each companion operation's arguments are built. A tool declaring a
	// companion must declare how to call it: a confirm takes the identity of
	// what was reserved, not the parameters the reservation was made with, and
	// only the tool knows which of its arguments carry that identity.
	ConfirmArguments    *CompanionArguments `protobuf:"bytes,10,opt,name=confirm_arguments,json=confirmArguments,proto3" json:"confirm_arguments,omitempty"`
	CancelArguments     *CompanionArguments `protobuf:"bytes,11,opt,name=cancel_arguments,json=cancelArguments,proto3" json:"cancel_arguments,omitempty"`
	CompensateArguments *CompanionArguments `protobuf:"bytes,12,opt,name=compensate_arguments,json=compensateArguments,proto3" json:"compensate_arguments,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TransactionSpec) Reset() {
	*x = TransactionSpec{}
	mi := &file_flory_gateway_v1_tool_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSpec) ProtoMessage() {}

func (x *TransactionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_tool_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSpec.ProtoReflect.Descriptor instead.
func (*TransactionSpec) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_tool_contract_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionSpec) GetEffectClass() EffectClass {
	if x != nil {
		return x.EffectClass
	}
	return EffectClass_EFFECT_CLASS_UNSPECIFIED
}

func (x *TransactionSpec) GetMode() ToolMode {
	if x != nil {
		return x.Mode
	}
	return ToolMode_TOOL_MODE_UNSPECIFIED
}

func (x *TransactionSpec) GetIdempotencyKeyPath() string {
	if x != nil {
		return x.IdempotencyKeyPath
	}
	return ""
}

func (x *TransactionSpec) GetIdempotentRetryable() bool {
	if x != nil && x.IdempotentRetryable != nil {
		return *x.IdempotentRetryable
	}
	return false
}

func (x *TransactionSpec) GetTryTimeoutS() uint32 {
	if x != nil {
		return x.TryTimeoutS
	}
	return 0
}

func (x *TransactionSpec) GetConfirmTool() string {
	if x != nil {
		return x.ConfirmTool
	}
	return ""
}

func (x *TransactionSpec) GetCancelTool() string {
	if x != nil {
		return x.CancelTool
	}
	return ""
}

func (x *TransactionSpec) GetCompensateTool() string {
	if x != nil {
		return x.CompensateTool
	}
	return ""
}

func (x *TransactionSpec) GetStatusTool() string {
	if x != nil {
		return x.StatusTool
	}
	return ""
}

func (x *TransactionSpec) GetConfirmArguments() *CompanionArguments {
	if x != nil {
		return x.ConfirmArguments
	}
	return nil
}

func (x *TransactionSpec) GetCancelArguments() *CompanionArguments {
	if x != nil {
		return x.CancelArguments
	}
	return nil
}

func (x *TransactionSpec) GetCompensateArguments() *CompanionArguments {
	if x != nil {
		return x.CompensateArguments
	}
	return nil
}

// How one companion operation's arguments are built from the try's own.
//
// Declared by the tool that owns the bracket, never inferred by an executor:
// passing the try's arguments through unchanged assumes the companion accepts
// them, and a companion whose schema is narrower — the usual case, since a
// confirm needs an identity rather than a description — is refused by the
// gateway at dispatch, after the pivot has already passed.
type CompanionArguments struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Companion parameter name -> JSONPath into this tool's own arguments.
	// A companion taking no arguments declares an empty map, which is a
	// statement rather than an omission.
	FromTryArguments map[string]string `protobuf:"bytes,1,rep,name=from_try_arguments,json=fromTryArguments,proto3" json:"from_try_arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompanionArguments) Reset() {
	*x = CompanionArguments{}
	mi := &file_flory_gateway_v1_tool_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanionArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanionArguments) ProtoMessage() {}

func (x *CompanionArguments) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_tool_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanionArguments.ProtoReflect.Descriptor instead.
func (*CompanionArguments) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_tool_contract_proto_rawDescGZIP(), []int{2}
}

func (x *CompanionArguments) GetFromTryArguments() map[string]string {
	if x != nil {
		return x.FromTryArguments
	}
	return nil
}

// The protocol contract for reaching a tool, separate from any endpoint address.
type AdapterSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wire protocol of the upstream. Only "grpc" is implemented.
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Protocol-specific operation selector, for documentation and future adapters.
	Operation     string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterSpec) Reset() {
	*x = AdapterSpec{}
	mi := &file_flory_gateway_v1_tool_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterSpec) ProtoMessage() {}

func (x *AdapterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_tool_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterSpec.ProtoReflect.Descriptor instead.
func (*AdapterSpec) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_tool_contract_proto_rawDescGZIP(), []int{3}
}

func (x *AdapterSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AdapterSpec) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// One immutable (tool_id, tool_version) contract.
type ToolContract struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ToolId      string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ToolVersion string                 `protobuf:"bytes,2,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema text. Tool payloads stay JSON Schema because that is what MCP
	// inputSchema and the planner consume; protobuf describes the envelope only.
	InputSchema  string `protobuf:"bytes,4,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema string `protobuf:"bytes,5,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	// Stable logical route identifier. In the digest; endpoint membership is not.
	RouteId           string            `protobuf:"bytes,6,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Adapter           *AdapterSpec      `protobuf:"bytes,7,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Txn               *TransactionSpec  `protobuf:"bytes,8,opt,name=txn,proto3" json:"txn,omitempty"`
	CompensationStyle CompensationStyle `protobuf:"varint,9,opt,name=compensation_style,json=compensationStyle,proto3,enum=flory.gateway.v1.CompensationStyle" json:"compensation_style,omitempty"`
	// Resource footprint used by check-rules R9 and R11, e.g. "inventory:{sku}".
	Footprint        []string          `protobuf:"bytes,10,rep,name=footprint,proto3" json:"footprint,omitempty"`
	Writes           []string          `protobuf:"bytes,11,rep,name=writes,proto3" json:"writes,omitempty"`
	TimeoutMs        uint32            `protobuf:"varint,12,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	RetryConstraints *RetryConstraints `protobuf:"bytes,13,opt,name=retry_constraints,json=retryConstraints,proto3" json:"retry_constraints,omitempty"`
	Owner            string            `protobuf:"bytes,14,opt,name=owner,proto3" json:"owner,omitempty"`
	// Business roles authorised to discover and execute this contract. The
	// reserved value "*" makes a tool public; an empty list is invalid.
	AllowedRoles []string `protobuf:"bytes,15,rep,name=allowed_roles,json=allowedRoles,proto3" json:"allowed_roles,omitempty"`
	// Control-flow field paths this tool's executor lifts out of its output and
	// into vertex/succeeded, e.g. "status" or "risk.score". A deterministic
	// router evaluates against these and nothing else, so a rule can decide a
	// branch without dereferencing the blob the bulk output streams to.
	LogFields     []string `protobuf:"bytes,16,rep,name=log_fields,json=logFields,proto3" json:"log_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolContract) Reset() {
	*x = ToolContract{}
	mi := &file_flory_gateway_v1_tool_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolContract) ProtoMessage() {}

func (x *ToolContract) ProtoReflect() protoreflect.Message {
	mi := &file_flory_gateway_v1_tool_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolContract.ProtoReflect.Descriptor instead.
func (*ToolContract) Descriptor() ([]byte, []int) {
	return file_flory_gateway_v1_tool_contract_proto_rawDescGZIP(), []int{4}
}

func (x *ToolContract) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolContract) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *ToolContract) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolContract) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *ToolContract) GetOutputSchema() string {
	if x != nil {
		return x.OutputSchema
	}
	return ""
}

func (x *ToolContract) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *ToolContract) GetAdapter() *AdapterSpec {
	if x != nil {
		return x.Adapter
	}
	return nil
}

func (x *ToolContract) GetTxn() *TransactionSpec {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *ToolContract) GetCompensationStyle() CompensationStyle {
	if x != nil {
		return x.CompensationStyle
	}
	return CompensationStyle_COMPENSATION_STYLE_UNSPECIFIED
}

func (x *ToolContract) GetFootprint() []string {
	if x != nil {
		return x.Footprint
	}
	return nil
}

func (x *ToolContract) GetWrites() []string {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *ToolContract) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ToolContract) GetRetryConstraints() *RetryConstraints {
	if x != nil {
		return x.RetryConstraints
	}
	return nil
}

func (x *ToolContract) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ToolContract) GetAllowedRoles() []string {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

func (x *ToolContract) GetLogFields() []string {
	if x != nil {
		return x.LogFields
	}
	return nil
}

var File_flory_gateway_v1_tool_contract_proto protoreflect.FileDescriptor

const file_flory_gateway_v1_tool_contract_proto_rawDesc = "" +
	"\n" +
	"$flory/gateway/v1/tool_contract.proto\x12\x10flory.gateway.v1\"\xb4\x01\n" +
	"\x10RetryConstraints\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\rR\vmaxAttempts\x12,\n" +
	"\x12initial_backoff_ms\x18\x02 \x01(\rR\x10initialBackoffMs\x12)\n" +
	"\x10multiplier_milli\x18\x03 \x01(\rR\x0fmultiplierMilli\x12$\n" +
	"\x0emax_backoff_ms\x18\x04 \x01(\rR\fmaxBackoffMs\"\xb5\x05\n" +
	"\x0fTransactionSpec\x12@\n" +
	"\feffect_class\x18\x01 \x01(\x0e2\x1d.flory.gateway.v1.EffectClassR\veffectClass\x12.\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1a.flory.gateway.v1.ToolModeR\x04mode\x120\n" +
	"\x14idempotency_key_path\x18\x03 \x01(\tR\x12idempotencyKeyPath\x126\n" +
	"\x14idempotent_retryable\x18\x04 \x01(\bH\x00R\x13idempotentRetryable\x88\x01\x01\x12\"\n" +
	"\rtry_timeout_s\x18\x05 \x01(\rR\vtryTimeoutS\x12!\n" +
	"\fconfirm_tool\x18\x06 \x01(\tR\vconfirmTool\x12\x1f\n" +
	"\vcancel_tool\x18\a \x01(\tR\n" +
	"cancelTool\x12'\n" +
	"\x0fcompensate_tool\x18\b \x01(\tR\x0ecompensateTool\x12\x1f\n" +
	"\vstatus_tool\x18\t \x01(\tR\n" +
	"statusTool\x12Q\n" +
	"\x11confirm_arguments\x18\n" +
	" \x01(\v2$.flory.gateway.v1.CompanionArgumentsR\x10confirmArguments\x12O\n" +
	"\x10cancel_arguments\x18\v \x01(\v2$.flory.gateway.v1.CompanionArgumentsR\x0fcancelArguments\x12W\n" +
	"\x14compensate_arguments\x18\f \x01(\v2$.flory.gateway.v1.CompanionArgumentsR\x13compensateArgumentsB\x17\n" +
	"\x15_idempotent_retryable\"\xc3\x01\n" +
	"\x12CompanionArguments\x12h\n" +
	"\x12from_try_arguments\x18\x01 \x03(\v2:.flory.gateway.v1.CompanionArguments.FromTryArgumentsEntryR\x10fromTryArguments\x1aC\n" +
	"\x15FromTryArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\vAdapterSpec\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"\x91\x05\n" +
	"\fToolContract\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12!\n" +
	"\ftool_version\x18\x02 \x01(\tR\vtoolVersion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x04 \x01(\tR\vinputSchema\x12#\n" +
	"\routput_schema\x18\x05 \x01(\tR\foutputSchema\x12\x19\n" +
	"\broute_id\x18\x06 \x01(\tR\arouteId\x127\n" +
	"\aadapter\x18\a \x01(\v2\x1d.flory.gateway.v1.AdapterSpecR\aadapter\x123\n" +
	"\x03txn\x18\b \x01(\v2!.flory.gateway.v1.TransactionSpecR\x03txn\x12R\n" +
	"\x12compensation_style\x18\t \x01(\x0e2#.flory.gateway.v1.CompensationStyleR\x11compensationStyle\x12\x1c\n" +
	"\tfootprint\x18\n" +
	" \x03(\tR\tfootprint\x12\x16\n" +
	"\x06writes\x18\v \x03(\tR\x06writes\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\f \x01(\rR\ttimeoutMs\x12O\n" +
	"\x11retry_constraints\x18\r \x01(\v2\".flory.gateway.v1.RetryConstraintsR\x10retryConstraints\x12\x14\n" +
	"\x05owner\x18\x0e \x01(\tR\x05owner\x12#\n" +
	"\rallowed_roles\x18\x0f \x03(\tR\fallowedRoles\x12\x1d\n" +
	"\n" +
	"log_fields\x18\x10 \x03(\tR\tlogFields*\x9b\x01\n" +
	"\vEffectClass\x12\x1c\n" +
	"\x18EFFECT_CLASS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EFFECT_CLASS_NONE\x10\x01\x12\x1b\n" +
	"\x17EFFECT_CLASS_BUFFERABLE\x10\x02\x12\x1b\n" +
	"\x17EFFECT_CLASS_REVERSIBLE\x10\x03\x12\x1d\n" +
	"\x19EFFECT_CLASS_IRREVERSIBLE\x10\x04*a\n" +
	"\bToolMode\x12\x19\n" +
	"\x15TOOL_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTOOL_MODE_PLAIN\x10\x01\x12\x11\n" +
	"\rTOOL_MODE_TCC\x10\x02\x12\x12\n" +
	"\x0eTOOL_MODE_SAGA\x10\x03*\x9f\x01\n" +
	"\x11CompensationStyle\x12\"\n" +
	"\x1eCOMPENSATION_STYLE_UNSPECIFIED\x10\x00\x12'\n" +
	"#COMPENSATION_STYLE_NOT_COMPENSATING\x10\x01\x12\x1c\n" +
	"\x18COMPENSATION_STYLE_DELTA\x10\x02\x12\x1f\n" +
	"\x1bCOMPENSATION_STYLE_SNAPSHOT\x10\x03BLZJgithub.com/linuxb/flory-ai/gatewayd/internal/pb/flory/gateway/v1;gatewayv1b\x06proto3"

var (
	file_flory_gateway_v1_tool_contract_proto_rawDescOnce sync.Once
	file_flory_gateway_v1_tool_contract_proto_rawDescData []byte
)

func file_flory_gateway_v1_tool_contract_proto_rawDescGZIP() []byte {
	file_flory_gateway_v1_tool_contract_proto_rawDescOnce.Do(func() {
		file_flory_gateway_v1_tool_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flory_gateway_v1_tool_contract_proto_rawDesc), len(file_flory_gateway_v1_tool_contract_proto_rawDesc)))
	})
	return file_flory_gateway_v1_tool_contract_proto_rawDescData
}

var file_flory_gateway_v1_tool_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_flory_gateway_v1_tool_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_flory_gateway_v1_tool_contract_proto_goTypes = []any{
	(EffectClass)(0),           // 0: flory.gateway.v1.EffectClass
	(ToolMode)(0),              // 1: flory.gateway.v1.ToolMode
	(CompensationStyle)(0),     // 2: flory.gateway.v1.CompensationStyle
	(*RetryConstraints)(nil),   // 3: flory.gateway.v1.RetryConstraints
	(*TransactionSpec)(nil),    // 4: flory.gateway.v1.TransactionSpec
	(*CompanionArguments)(nil), // 5: flory.gateway.v1.CompanionArguments
	(*AdapterSpec)(nil),        // 6: flory.gateway.v1.AdapterSpec
	(*ToolContract)(nil),       // 7: flory.gateway.v1.ToolContract
	nil,                        // 8: flory.gateway.v1.CompanionArguments.FromTryArgumentsEntry
}
var file_flory_gateway_v1_tool_contract_proto_depIdxs = []int32{
	0,  // 0: flory.gateway.v1.TransactionSpec.effect_class:type_name -> flory.gateway.v1.EffectClass
	1,  // 1: flory.gateway.v1.TransactionSpec.mode:type_name -> flory.gateway.v1.ToolMode
	5,  // 2: flory.gateway.v1.TransactionSpec.confirm_arguments:type_name -> flory.gateway.v1.CompanionArguments
	5,  // 3: flory.gateway.v1.TransactionSpec.cancel_arguments:type_name -> flory.gateway.v1.CompanionArguments
	5,  // 4: flory.gateway.v1.TransactionSpec.compensate_arguments:type_name -> flory.gateway.v1.CompanionArguments
	8,  // 5: flory.gateway.v1.CompanionArguments.from_try_arguments:type_name -> flory.gateway.v1.CompanionArguments.FromTryArgumentsEntry
	6,  // 6: flory.gateway.v1.ToolContract.adapter:type_name -> flory.gateway.v1.AdapterSpec
	4,  // 7: flory.gateway.v1.ToolContract.txn:type_name -> flory.gateway.v1.TransactionSpec
	2,  // 8: flory.gateway.v1.ToolContract.compensation_style:type_name -> flory.gateway.v1.CompensationStyle
	3,  // 9: flory.gateway.v1.ToolContract.retry_constraints:type_name -> flory.gateway.v1.RetryConstraints
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_flory_gateway_v1_tool_contract_proto_init() }
func file_flory_gateway_v1_tool_contract_proto_init() {
	if File_flory_gateway_v1_tool_contract_proto != nil {
		return
	}
	file_flory_gateway_v1_tool_contract_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flory_gateway_v1_tool_contract_proto_rawDesc), len(file_flory_gateway_v1_tool_contract_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flory_gateway_v1_tool_contract_proto_goTypes,
		DependencyIndexes: file_flory_gateway_v1_tool_contract_proto_depIdxs,
		EnumInfos:         file_flory_gateway_v1_tool_contract_proto_enumTypes,
		MessageInfos:      file_flory_gateway_v1_tool_contract_proto_msgTypes,
	}.Build()
	File_flory_gateway_v1_tool_contract_proto = out.File
	file_flory_gateway_v1_tool_contract_proto_goTypes = nil
	file_flory_gateway_v1_tool_contract_proto_depIdxs = nil
}
